// Navigation and footer content for the hand-written chrome.
//
// Menu content lives in menu-data.json, generated by `npm run chrome:menu` from
// the vendored snapshot — the mega menus are ~100 links across nested columns,
// which is a lot to maintain by hand. Footer content below is hand-maintained.
//
// This is the file to edit when a footer link changes; edit menu-data.json (or
// re-run the extractor) for menu changes.

import menus from "./menu-data.json"

export interface NavLink {
  label: string
  href: string
  /** Renders in the accent colour as a section's "see all" row. */
  feature?: boolean
}

export interface MenuLink {
  label: string
  href: string
}

export interface MenuGroup extends MenuLink {
  /** Filename under public/chrome/menu-icons/, if the group has one. */
  icon: string | null
  links: MenuLink[]
}

export interface MenuColumn {
  heading: string
  groups: MenuGroup[]
}

export interface MegaMenu {
  label: string
  kind: "mega"
  columns: MenuColumn[]
  promo: { text: string; cta: MenuLink | null; buttons: MenuLink[] }
}

export interface ListMenu {
  label: string
  kind: "list"
  links: MenuLink[]
}

export type Menu = MegaMenu | ListMenu

// The desktop nav, in order. menu-data.json also carries the mobile-only panels
// (Technology Expertise, About Us, Resources), so select rather than take all.
// Regenerate the JSON with `npm run chrome:menu`.
const ORDER = ["Services", "Portfolio", "About", "Free Tools"] as const

const TOP_LEVEL_HREF: Record<string, string> = {
  Services: "/product-development-services/",
  Portfolio: "/portfolio-industry/",
  About: "/company/",
  "Free Tools": "https://planning.design1st.com/",
}

export const nav: Array<Menu & { href: string }> = ORDER.map((label) => {
  const menu = (menus as Menu[]).find((m) => m.label === label)
  if (!menu) throw new Error(`menu-data.json is missing "${label}" — re-run npm run chrome:menu`)
  return { ...menu, href: TOP_LEVEL_HREF[label] }
})

/** Footer link columns, grouped exactly as the live footer renders them. */
export const footerGroups = [
  {
    heading: "Expertise",
    /** Where the list breaks into its second column. The live footer breaks in
     *  a different place at tablet, so both are recorded. */
    splitAt: 3,
    tabletSplitAt: 4,
    links: [
      { label: "Product Strategy", href: "/product-plan/" },
      { label: "Industrial Design", href: "/industrial-design/" },
      { label: "Mechanical Engineering", href: "/mechanical-engineering/" },
      { label: "Prototype and Test", href: "/prototype-manufacturing-services/" },
      { label: "Electronic Engineering", href: "/electronic-design-services/" },
      { label: "Embedded Software", href: "/embedded-software/" },
      { label: "Manufacturing Support", href: "/manufacturing/" },
    ],
  },
  {
    heading: "Resources",
    headingHref: "/blog",
    splitAt: 4,
    tabletSplitAt: 4,
    links: [
      { label: "Articles", href: "/blog/" },
      { label: "Newsroom", href: "/newsroom/" },
      { label: "Case Studies", href: "/case-studies/" },
      { label: "About Us", href: "/company/" },
      { label: "Industry Portfolio", href: "/portfolio-industry/" },
      { label: "Technology Portfolio", href: "/portfolio-technology/" },
      { label: "Our Process", href: "/product-development-process/" },
      { label: "Careers", href: "/careers/" },
    ],
  },
] satisfies Array<{
  heading: string
  headingHref?: string
  links: NavLink[]
}>

/** Award/partner badges in the footer strip, in the order the live site shows
 *  them. Sizes are the rendered sizes measured at 1440 — set explicitly so the
 *  row doesn't reflow as these lazy-load in. */
export const badges = [
  { file: "image-317.webp", w: 83, h: 19, alt: "Professional Engineers Ontario" },
  { file: "image-319.webp", w: 76, h: 40, alt: "Grands Prix du Design — Gold Winner" },
  { file: "image-320.webp", w: 48, h: 40, alt: "Clutch Top Product Design Company" },
  { file: "image-321.webp", w: 62, h: 40, alt: "A'Design Award Winner 2020" },
  { file: "image-322-1.webp", w: 85, h: 40, alt: "Mining Technology Excellence Awards" },
  { file: "image-318-1.webp", w: 88, h: 20, alt: "ACIDO" },
  { file: "image-323-1.webp", w: 52, h: 40, alt: "Award" },
  { file: "top-product-design-companies-1-1-1-1.webp", w: 34, h: 52, alt: "Top Product Design Companies" },
  { file: "image-324.webp", w: 40, h: 40, alt: "The Irish Laboratory Awards 2020 Winner" },
] as const

export const social = [
  { label: "Facebook", href: "https://www.facebook.com/Design1st", icon: "facebookF" },
  { label: "Linkedin", href: "https://ca.linkedin.com/company/design1st/", icon: "linkedinIn" },
  { label: "Twitter", href: "https://twitter.com/Design_1st", icon: "twitter" },
  { label: "Youtube", href: "https://www.youtube.com/user/design1st/feed", icon: "youtube" },
  { label: "Instagram", href: "https://www.instagram.com/design_1st", icon: "instagram" },
] as const
